"""empty message

Revision ID: 24ed1d0a4fb7
Revises: 
Create Date: 2020-05-21 23:55:22.585625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ed1d0a4fb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernames', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'user', ['usernames'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'usernames')
    # ### end Alembic commands ###
