"""empty message

Revision ID: 76568ed2f720
Revises: b38a48b2c821
Create Date: 2020-05-22 00:17:24.686933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76568ed2f720'
down_revision = 'b38a48b2c821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=33),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=33),
               existing_nullable=True)
    # ### end Alembic commands ###
