"""empty message

Revision ID: b38a48b2c821
Revises: e1e2ed8a4e7c
Create Date: 2020-05-22 00:16:54.490868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b38a48b2c821'
down_revision = 'e1e2ed8a4e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=33),
               existing_nullable=True)
    op.alter_column('user', 'usernames',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=160),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'usernames',
               existing_type=sa.String(length=160),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=33),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
