"""empty message

Revision ID: eb2214c06da6
Revises: 76568ed2f720
Create Date: 2020-05-22 00:22:00.977064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb2214c06da6'
down_revision = '76568ed2f720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('usernames', table_name='user')
    op.drop_column('user', 'usernames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernames', mysql.VARCHAR(length=160), nullable=True))
    op.create_index('usernames', 'user', ['usernames'], unique=True)
    # ### end Alembic commands ###
